name: pulse-front
on:
  push:
    branches: [ main ] 
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' # pulse-fron 의 node 버전은 22.2.0 
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_IP }}
        username: ec2-user 
        key: ${{ secrets.EC2_SSH_KEY }}
        script: | # pulse의 최초 실행 고려한 스크립트
          if [ ! -d "/home/ec2-user/pulse-front" ]; then
            mkdir -p /home/ec2-user/pulse-front
          fi
          
          if [ ! -d "/home/ec2-user/pulse-front/.git" ]; then
            cd /home/ec2-user/pulse-front
            git init
            git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git
            git fetch
            git checkout -f main
          else
            cd /home/ec2-user/pulse-front
            git fetch
            git reset --hard origin/main
          fi
          
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          
          npm ci
          npm run build
