name: pulse-front
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        
    # 환경 변수 파일 생성 부분
    - name: env
      run: |
        touch .env.production
        echo "MODE=production" >> .env.production
        echo "DOMAIN=http://pulse-dev.shop" >> .env.production
        echo "VITE_PROD_API_URL=${{ secrets.VITE_PROD_API_URL }}" >> .env.production
        echo "VERSION=v1" >> .env.production
        echo "VITE_NAVER_CLIENT_ID=${{ secrets.VITE_NAVER_CLIENT_ID }}" >> .env.production
        
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Debug build directory
      run: |
        echo "현재 디렉토리 확인:"
        ls -la build || echo "build 디렉토리 없음"
        echo "dist 디렉토리 확인:"
        ls -la dist || echo "dist 디렉토리 없음"
    - name: Deploy to EC2
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        # dist 디렉토리만 사용하도록 명확하게 지정
        scp -i private_key.pem -o StrictHostKeyChecking=no -r dist/* ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user/pulse-front/
        ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} 'bash -s' << 'ENDSSH'
          # Nginx 설정이 있다면 재시작
          sudo systemctl restart nginx ENDSSH
