name: pulse-front

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' # 현재 pulse의 node 버전은 22.2.0
        
    - name: Install dependencies
      run: npm ci # 또는 yarn install --frozen-lockfile
      
    - name: Build
      run: npm run build # 또는 yarn build
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_IP }}
        username: ec2-user 
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/pulse-front
          git pull
          npm ci
          npm run build
